config/routes.rb
HtmlUpload::Application.routes.draw do
  resources :webpages

  root :to => 'webpages#index'

  match "/iamadmin" => "webpages#admin"

end

app/models/webpage.rb
class Webpage < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/webpages_controller.rb
class WebpagesController < ApplicationController
  # GET /webpages
  # GET /webpages.json
  def index
    @webpages = Webpage.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @webpages }
    end
  end

  def admin
    @webpages = Webpage.all
  end

  # GET /webpages/1
  # GET /webpages/1.json
  def show
    @webpage = Webpage.find(params[:id])
    render :layout => false and return

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @webpage }
    end
  end

  # GET /webpages/new
  # GET /webpages/new.json
  def new
    @webpage = Webpage.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @webpage }
    end
  end

  # GET /webpages/1/edit
  def edit
    @webpage = Webpage.find(params[:id])
  end

  # POST /webpages
  # POST /webpages.json
  def create
    @webpage = Webpage.new(params[:webpage])

    respond_to do |format|
      if @webpage.save
        format.html { redirect_to @webpage, notice: 'Webpage was successfully created.' }
        format.json { render json: @webpage, status: :created, location: @webpage }
      else
        format.html { render action: "new" }
        format.json { render json: @webpage.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /webpages/1
  # PUT /webpages/1.json
  def update
    @webpage = Webpage.find(params[:id])

    respond_to do |format|
      if @webpage.update_attributes(params[:webpage])
        format.html { redirect_to @webpage, notice: 'Webpage was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @webpage.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /webpages/1
  # DELETE /webpages/1.json
  def destroy
    @webpage = Webpage.find(params[:id])
    @webpage.destroy

    respond_to do |format|
      format.html { redirect_to webpages_url }
      format.json { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/webpages_helper.rb
module WebpagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CoderDojoNYC - Upload Your Code :)</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="span9"><%= yield %></div>

</body>
</html>

app/views/webpages/_form.html.erb
<%= form_for @webpage, :html => { :class => 'form-horizontal' } do |f| %>
  <fieldset>
    <legend><%= controller.action_name.capitalize %> Webpage</legend>

    <div class="control-group">
      <%= f.label :pagename, :class => 'control-label' %>
      <div class="controls">
	<%= f.text_field :pagename, :class => 'text_field span6' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :html, "HTML", :class => 'control-label' %>
      <div class="controls">
        <%= f.text_area :html, :class => 'text_area span6' %>
      </div>
    </div>

    <div class="form-actions">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to 'Cancel', webpages_path, :class => 'btn' %>
    </div>
  </fieldset>
<% end %>

app/views/webpages/admin.html.erb
<h1>Webpages</h1>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Pagename</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @webpages.each do |webpage| %>
      <tr>
        <td><%= link_to webpage.pagename, webpage_path(webpage) %></td>
        <td>
          <%= link_to 'Edit', edit_webpage_path(webpage), :class => 'btn btn-mini' %>
          <%= link_to 'Destroy', webpage, :confirm => 'Are you sure?', :method => :delete %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New', new_webpage_path, :class => 'btn btn-primary' %>

app/views/webpages/edit.html.erb
<%= render :partial => 'form' %>

app/views/webpages/index.html.erb
<h1>Webpages</h1>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Pagename</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @webpages.each do |webpage| %>
      <tr>
        <td><%= link_to webpage.pagename, webpage_path(webpage) %></td>
        <td>
          <%= link_to 'Edit', edit_webpage_path(webpage), :class => 'btn btn-mini' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New', new_webpage_path, :class => 'btn btn-primary' %>

app/views/webpages/new.html.erb
<%= render :partial => 'form' %>

app/views/webpages/show.html.erb
<!--This is part of CoderDojo Code -->
<!--===========================================-->
<p id="notice"><%= notice %></p>

<p>
<b>Pagename:</b>
<%= @webpage.pagename %>
</p>

<%= link_to "Home", "/" %> |
<%= link_to "Edit this Page", edit_webpage_path(@webpage) %> |
<%= link_to "Go Back", webpages_path %>
<p>The HTML You Added Creates The Following Page:</p>
<hr />
<!--===========================================-->
<!--Everything below this part is your own HTML -->

<%= raw @webpage.html %>